export const sources = [
  { id: 'microsoft-ai', name: '微软AI', siteUrl: 'https://blogs.microsoft.com/ai/', feedUrl: 'https://blogs.microsoft.com/ai/feed/', category: '公司研究', color: '#0A84FF', colorAlt: '#5AC8FA' },
  { id: 'msra', name: '微软亚研', siteUrl: 'https://www.msra.cn/', feedUrl: 'https://www.msra.cn/feed', category: '公司研究', color: '#0078D4', colorAlt: '#50E6FF' },
  { id: 'pytorch', name: 'PyTorch Blog', siteUrl: 'https://pytorch.org/blog/', feedUrl: 'https://pytorch.org/feed.xml', category: '框架与工具', color: '#EE4C2C', colorAlt: '#FF8A65' },
  { id: 'meta-ai', name: 'Meta AI Blog', siteUrl: 'https://ai.facebook.com/blog/', category: '公司研究', color: '#0668E1', colorAlt: '#8AB4F8' },
  { id: 'google-ai', name: 'Google AI Blog', siteUrl: 'https://blog.google/innovation-and-ai/technology/ai/', feedUrl: 'https://blog.google/innovation-and-ai/technology/ai/rss/', category: '公司研究', color: '#4285F4', colorAlt: '#34A853' },
  { id: 'openai', name: 'OpenAI Blog', siteUrl: 'https://openai.com/blog/', feedUrl: 'https://openai.com/news/rss.xml', category: '公司研究', color: '#10A37F', colorAlt: '#6EE7C4' },
  { id: 'deepmind', name: 'DeepMind Blog', siteUrl: 'https://deepmind.com/blog', feedUrl: 'https://deepmind.google/blog/rss.xml', category: '公司研究', color: '#6C5CE7', colorAlt: '#00C2FF' },
  { id: 'meituan-tech', name: '美团技术团队', siteUrl: 'https://tech.meituan.com/', feedUrl: 'https://tech.meituan.com/feed/', category: '中文技术', color: '#FFD100', colorAlt: '#FF8A00' },
  { id: 'zhihu-daily', name: '知乎每日精选', siteUrl: 'https://www.zhihu.com/', feedUrl: 'https://www.zhihu.com/rss', category: '中文技术', color: '#0084FF', colorAlt: '#58B3FF' },
  { id: 'hankcs', name: '码农场', siteUrl: 'https://www.hankcs.com/', feedUrl: 'https://www.hankcs.com/feed/', category: '中文技术', color: '#5B8FF9', colorAlt: '#61DDAA' },
  { id: 'yongyuan', name: "Yong's Blog", siteUrl: 'https://yongyuan.name/blog/', feedUrl: 'https://yongyuan.name/blog/feed.xml', category: '个人博客', color: '#7C3AED', colorAlt: '#C084FC' },
  { id: 'jalammar', name: "Jay Alammar's Blog", siteUrl: 'http://jalammar.github.io/', feedUrl: 'http://jalammar.github.io/feed.xml', category: '个人博客', color: '#F97316', colorAlt: '#FACC15' },
  { id: 'deeplearn-me', name: '算法之道', siteUrl: 'https://www.deeplearn.me/', category: '中文技术', color: '#E11D48', colorAlt: '#FB7185' },
  { id: 'karpathy', name: 'Andrej Karpathy Blog', siteUrl: 'https://karpathy.github.io/', feedUrl: 'https://karpathy.github.io/feed.xml', category: '个人博客', color: '#111827', colorAlt: '#6B7280' },
  { id: 'ruder', name: 'Sebastian Ruder', siteUrl: 'https://ruder.io/', feedUrl: 'https://ruder.io/rss/index.rss', category: '个人博客', color: '#0891B2', colorAlt: '#67E8F9' },
  { id: 'mlmastery', name: 'Jason Brownlee', siteUrl: 'https://machinelearningmastery.com/blog/', feedUrl: 'https://machinelearningmastery.com/blog/feed/', category: '个人博客', color: '#2563EB', colorAlt: '#93C5FD' },
  { id: 'distill', name: 'Distill', siteUrl: 'https://distill.pub/', feedUrl: 'https://distill.pub/rss.xml', category: '学术研究', color: '#B45309', colorAlt: '#FBBF24' },
  { id: 'bair', name: 'BAIR Blog', siteUrl: 'https://bair.berkeley.edu/blog/', feedUrl: 'https://bair.berkeley.edu/blog/feed.xml', category: '学术研究', color: '#003262', colorAlt: '#FDB515' },
  { id: 'colah', name: "colah's blog", siteUrl: 'http://colah.github.io/', feedUrl: 'http://colah.github.io/rss.xml', category: '个人博客', color: '#D946EF', colorAlt: '#F0ABFC' },
  { id: 'inference-vc', name: 'inFERENCe', siteUrl: 'https://www.inference.vc/', category: '个人博客', color: '#DC2626', colorAlt: '#FCA5A5' },
  { id: 'pete-warden', name: 'Pete Warden', siteUrl: 'https://petewarden.com/', feedUrl: 'https://petewarden.com/feed/', category: '个人博客', color: '#65A30D', colorAlt: '#BEF264' },
  { id: 'jeremy-jordan', name: 'Jeremy Jordan', siteUrl: 'https://www.jeremyjordan.me/', feedUrl: 'https://www.jeremyjordan.me/feed.xml', category: '个人博客', color: '#0F766E', colorAlt: '#5EEAD4' },
  { id: 'graduate-descent', name: 'Graduate Descent', siteUrl: 'http://timvieira.github.io/blog/', feedUrl: 'http://timvieira.github.io/blog/atom.xml', category: '个人博客', color: '#9333EA', colorAlt: '#D8B4FE' },
  { id: 'lilian-weng', name: "Lil'Log", siteUrl: 'https://lilianweng.github.io/', feedUrl: 'https://lilianweng.github.io/index.xml', category: '个人博客', color: '#DB2777', colorAlt: '#F9A8D4' },
  { id: 'nvidia', name: 'NVIDIA Blog', siteUrl: 'https://blogs.nvidia.com/', feedUrl: 'https://blogs.nvidia.com/feed/', category: '公司研究', color: '#76B900', colorAlt: '#B7E34A' },
  { id: 'eric-jang', name: 'Eric Jang', siteUrl: 'https://blog.evjang.com/', feedUrl: 'https://blog.evjang.com/feeds/posts/default', category: '个人博客', color: '#14B8A6', colorAlt: '#99F6E4' },
  { id: 'christabella', name: 'Christabella Irwanto', siteUrl: 'https://bella.cc/blog/', category: '个人博客', color: '#F43F5E', colorAlt: '#FDA4AF' },
  { id: 'jonty-sinai', name: 'Jonty Sinai', siteUrl: 'https://jontysinai.github.io/', category: '个人博客', color: '#4F46E5', colorAlt: '#A5B4FC' },
  { id: 'lei-mao', name: 'Lei Mao', siteUrl: 'https://leimao.github.io/blog/', feedUrl: 'https://leimao.github.io/blog/feed.xml', category: '个人博客', color: '#0284C7', colorAlt: '#7DD3FC' },
  { id: 'amitness', name: 'Amit Chaudhary', siteUrl: 'https://amitness.com/', feedUrl: 'https://amitness.com/index.xml', category: '个人博客', color: '#EA580C', colorAlt: '#FDBA74' },
  { id: 'sander-dieleman', name: 'Sander Dieleman', siteUrl: 'https://benanne.github.io/', feedUrl: 'https://benanne.github.io/feed.xml', category: '个人博客', color: '#6366F1', colorAlt: '#C7D2FE' },
  { id: 'causal-analysis', name: 'Causal Analysis in Theory and Practice', siteUrl: 'http://causality.cs.ucla.edu/blog/', feedUrl: 'http://causality.cs.ucla.edu/blog/index.php/feed/', category: '学术研究', color: '#7E22CE', colorAlt: '#E879F9' },
  { id: 'hunch', name: 'Machine learning and learning theory research', siteUrl: 'https://hunch.net/', feedUrl: 'https://hunch.net/?feed=rss2', category: '学术研究', color: '#B91C1C', colorAlt: '#F87171' },
  { id: 'shusen-wang', name: 'ShusenWang', siteUrl: 'https://www.youtube.com/c/ShusenWang/videos', category: '视频', color: '#FF0000', colorAlt: '#FF6B6B' },
  { id: 'offconvex', name: 'offconvex', siteUrl: 'http://www.offconvex.org/', feedUrl: 'http://www.offconvex.org/feed/', category: '学术研究', color: '#0D9488', colorAlt: '#5EEAD4' },
  { id: 'pythonspeed', name: 'Python⇒Speed', siteUrl: 'https://pythonspeed.com/', feedUrl: 'https://pythonspeed.com/atom.xml', category: '框架与工具', color: '#3776AB', colorAlt: '#FFD343' },
  { id: 'huggingface', name: 'Hugging Face', siteUrl: 'https://huggingface.co/blog', feedUrl: 'https://huggingface.co/blog/feed.xml', category: '框架与工具', color: '#FFBD2E', colorAlt: '#FF8A00' },
  { id: 'wandb', name: 'Weights & Biases', siteUrl: 'https://wandb.ai/fully-connected', category: '框架与工具', color: '#FFBE00', colorAlt: '#8BD9DD' },
  { id: 'han-xiao', name: 'Han Xiao', siteUrl: 'https://hanxiao.io/archives/', category: '个人博客', color: '#334155', colorAlt: '#94A3B8' },
]
